Config = {}

-- ═══════════════════════════════════════════════════════════════════
--  HD DISPATCH | HAZY DEVELOPMENT | v1.0.0
--  Advanced dispatch: 999 calls route to United Kingdom Police /
--  United Kingdom Health Service, and vehicle breakdowns route to
--  recovery. Talks to the framework the same way every other resource
--  in this ecosystem does — exports['qb-core']:GetCoreObject() — so
--  it needs zero changes if HD_Framework's internals ever change.
-- ═══════════════════════════════════════════════════════════════════

-- ═══════════════════════════ CALL TYPES ═════════════════════════════
-- `jobs` matches by exact job name. `jobType` matches ANY job whose
-- shared/jobs.lua entry has that `type` — this is what makes recovery
-- calls reach every mechanic-type job automatically, not just the
-- stock 'mechanic' job. A call type can use either or both.
Config.CallTypes = {
    police = {
        label = 'United Kingdom Police',
        code = 'POLICE',
        jobs = { 'police' },
        jobType = nil,
        header = '#0B2447',
        accent = '#3E7CB1',
        blipSprite = 60,
        blipColor = 3,
    },
    ems = {
        label = 'United Kingdom Health Service',
        code = 'UHS',
        jobs = { 'ambulance' },
        jobType = nil,
        header = '#4B5320',
        accent = '#8A9A5B',
        blipSprite = 61,
        blipColor = 2,
    },
    recovery = {
        label = 'Vehicle Recovery',
        code = 'RECOVERY',
        jobs = {},
        jobType = 'mechanic',
        header = '#5A3B12',
        accent = '#D8892B',
        blipSprite = 68,
        blipColor = 5,
    },
}

-- ═══════════════════════════ PRIORITY GRADES ════════════════════════
-- Matches real UK police call-grading terminology (Grade 1 Immediate,
-- Grade 2 Priority, Grade 3 Scheduled) so it reads authentically.
Config.PriorityGrades = {
    [1] = { name = 'Grade 1 — Immediate', color = '#C4453A' },
    [2] = { name = 'Grade 2 — Priority', color = '#D8A23E' },
    [3] = { name = 'Grade 3 — Scheduled', color = '#3E7CB1' },
}
Config.DefaultPriority = 2

-- ═══════════════════════════ DUTY GATING ════════════════════════════
-- Only on-duty members of a matching job ever see or receive a call.
Config.RequireDuty = true

-- ═══════════════════════════ COMMANDS / KEYBIND ═════════════════════
Config.Commands = {
    call999 = '999',      -- civilians: report a police or medical emergency
    recovery = 'recovery', -- civilians: request vehicle recovery for their current car
}
Config.Keybind = 'F5'      -- opens the dispatch board for on-duty responders (rebindable in FiveM settings)

-- ═══════════════════════════ LIMITS ═════════════════════════════════
-- Calls aren't persisted to a database in v1 — closed calls just drop
-- off the live board. This only caps how many cards the NUI renders
-- at once on a very busy server; the server never drops a real call.
Config.MaxLiveCalls = 60

-- ═══════════════════════════ AUTOMATIC CALLS ════════════════════════
-- Generated by the game itself rather than a player dialling in.
Config.AutoTriggers = {
    ShotsFired = {
        Enabled = true,
        CooldownSeconds = 20, -- per shooter, stops one gunfight spamming the board
        MergeRadius = 40.0,   -- shots within this radius of an existing open shots-fired call bump it instead of opening a new one
        Priority = 1,
    },
    PlayerDowned = {
        Enabled = true,
        Priority = 1,
    },
}

-- ═══════════════════════════ SOUND ══════════════════════════════════
Config.Sound = {
    Enabled = true, -- alert tone is generated in-browser (Web Audio API), no audio files shipped
}

-- ═══════════════════════════ NOTIFY ══════════════════════════════════
-- Replace with your own notify export if desired — matches hazy_mdt's
-- Config.Notify convention.
Config.Notify = function(msg, ntype)
    SetNotificationTextEntry('STRING')
    AddTextComponentString(msg)
    DrawNotification(false, false)
end
